import type { Metadata } from 'next'
import './globals.css'
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/nprogress/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import theme from './theme';
import { Notifications } from '@mantine/notifications';
import { RouterTransition } from '../lib/components/nProgress';
import { ModalsProvider } from '@mantine/modals';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body >
        <MantineProvider theme={theme}>
          <Notifications />
          <RouterTransition />
          <ModalsProvider >
            {children}
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
